### ISSUE TITLE
dynamic linking failure

### ISSUE THREAD

**Issue by iotamudelta** [flame/libflame#14]
This looks similar to the BLIS issue I had reported there and had been fixed. A bunch of these happen:

`/usr/bin/ld: error: can't create dynamic relocation R_X86_64_PC32 against symbol: FLA_Obj_attach_buffer in readonly segment; recompile object files with -fPIC
>>> defined in obj/amd64-portbld-freebsd12.0/base/flamec/main/FLA_Obj.o
>>> referenced by FLA_gebrd.c
>>>               obj/amd64-portbld-freebsd12.0/map/lapack2flamec/FLA_gebrd.o:(sgebrd_)`

upon linking with lld 6.0.0 on FreeBSD 12-HEAD

**Comment by fgvanzee** [comment]
@iotamudelta Do you happen to remember which BLIS issue that was?

**Comment by iotamudelta** [comment]
@fgvanzee [#179](https://github.com/flame/blis/issues/179)

**Comment by fgvanzee** [comment]
Thanks. I think it was commit [8912e68](https://github.com/flame/blis/commit/8912e6886b97eabb4ce0c35a3609a0fd994d347b) that fixed your issue. I'll look into this for libflame.

**Comment by iotamudelta** [comment]
Thanks for looking into this!

**Comment by fgvanzee** [comment]
@iotamudelta Actually, could you first confirm that you configured with `--enable-dynamic-build`? `configure` disables shared library generation by default.

BTW, you may want to check out the script `run-conf/run-configure.sh`. It allows you to easily enable/disable lots of options and see them all at once. The options there are *mostly* defaults, but if in doubt, you should run through the list to make sure it has/omits what you want.

**Comment by iotamudelta** [comment]
@fgvanzee Yes, I am enabling both dynamic and shared: 

` $ ./configure --enable-dynamic-build --enable-max-arg-list-hack --enable-lapack2flame --enable-multithreading=pthreads --enable-supermatrix --disable-autodetect-f77-ldflags --disable-autodetect-f77-name-mangling --enable-vector-intrins
ics=none --disable-ldim-alignment --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/ --build=amd64-portbld-freebsd12.0`

This is for the purpose of having a Fortran-free LAPACK. Let me know if there is anything missing/wrong!

I saw the script - the issue is that for the port it's probably better/easier for us to call configure directly (as that triggers export of the correct $CC, $CFLAGS, ... from within our ports collection).

**Comment by fgvanzee** [comment]
That looks fine, except that there is a stray space in the vector intrinsics option. Also, be aware that all of the options after `--prefix` are currently ignored by libflame's `configure`. (Not ideal, I know. libflame, its build system included, deserves a lot of TLC that I can't really spare right now, and that would be one of the things I'd address.)

**Comment by iotamudelta** [comment]
That space may be wrap around, it is correct in the config.log .

Thanks for letting me know concerning prefix. I don't think these options matter (they are auto-options coming from FBSD)

**Comment by fgvanzee** [comment]
I did a build of libflame with compile-time verbosity enabled, and I confirmed that `-fPIC` was used to compile every file. (And I observed no errors when the `.so` was generated.) I didn't use exactly your configure options, though, and I hadn't pulled in your recent pull request commit. So I'm reconfiguring/recompiling to be sure.

**Comment by iotamudelta** [comment]
@fgvanzee I am also recompiling, will take some time. Could this be some OS-dependent switch?

**Comment by fgvanzee** [comment]
@iotamudelta My rebuild yielded the same result: I can't reproduce your error. :-\

> Could this be some OS-dependent switch?

It's anyone's guess.

Perhaps you could try the following (after pulling in a very recent commit in which I added support for `V=1`):
```
$ make [-jN] V=1 > make.out 2> make.err
$ grep gcc make.out | wc
   4615 1181188 40795796
$ grep fPIC make.out | wc
   4614 1181182 40795670
$ grep gcc make.out | grep -v fPIC
gcc -shared -Wl,-soname,libflame.so -o lib/x86_64-unknown-linux-gnu/libflame.so
@lib/x86_64-unknown-linux-gnu/libflame.so.in
```
As you can see, the above output suggests that the only line in the output that did not contain -fPIC was the shared object link command.

If you want the build to go faster for the time being, I recommend disabling lapack2flamec.

**Comment by iotamudelta** [comment]
OK, first recompilation yielded the same linking error, so I am not being crazy. Indeed subsequent verbose compilation indicates that none of the files get fPIC passed, so it's probably an OS or compiler dependent problem (since FreeBSD uses cc which is clang). I'll see if I can locate it.

**Comment by iotamudelta** [comment]
I believe this is due to the ports collection defining CFLAGS and if CFLAGS are defined, the libflame make system overrides whatever flags it came up with internally with these CFLAGS. I guess there are good reasons for doing that as opposed to appending the internal CFLAGS to the external ones?

**Comment by fgvanzee** [comment]
>I believe this is due to the ports collection defining CFLAGS

@iotamudelta Yeah, that would do it. In theory, the idea of overriding `CFLAGS` was always nice, but I'm not sure in practice how man people used it. (My guess is the number is very small.)

I see two options:
1. Change the variable name to something else, such as `OVERRIDE_CFLAGS`. Only if this value is non-empty does it override `CFLAGS`. If it is empty, libflame's compiler options are appended to CFLAGS. (This would obviate `EXTRA_CFLAGS` and its related configure option.)
2. Unconditionally append libflame's compiler options to `CFLAGS`. (This would also obviate `EXTRA_CFLAGS`.)

(1) is more flexible, but also more work. (2) is simpler and will probably work in most cases. Neither option is ideal, but then again, neither is the status quo.

The main problem (with either option) is that appending introduces uncertainty, in that it would be possible for a user to bungle a libflame build because his CFLAGS had some brain-dead options pre-set (by whomever).

**Comment by iotamudelta** [comment]
@fgvanzee It seems to me then that 1) is the better option? I do agree that numerical libraries are really not the kind of thing you want to apply random flags to.

**Comment by fgvanzee** [comment]
@iotamudelta I'm leaning toward (2). Unless you have an immediate need for `OVERRIDE_CFLAGS`, I suggest we punt until someone asks for it.

**Comment by iotamudelta** [comment]
@fgvanzee took a bit longer than I hoped since I needed to fix some more items in the port but it seems to work now. Works,thank you so much!

One more question: ldd on the shared library does not point to anything but libc. How can I see from the compilation if it correctly picked up BLIS as its external BLAS dependency?

**Comment by iotamudelta** [comment]
@fgvanzee NM, I see the BLAS symbols appear as undefined - so all should be well. Closing this, thanks again!

**Comment by fgvanzee** [comment]
@iotamudelta Yes, BLAS is not integrated into libflame. (It actually has an optional built-in BLAS, but it is not included by default and few people use it since it is low-performance.) The user must link against his preferred BLAS when building the application.
