### ISSUE TITLE
missing symbols in static library

### ISSUE THREAD

**Issue by migueldiascosta** [flame/libflame#17]
Hello, 

I'm building libflame with `-enable-max-arg-list-hack --enable-lapack2flame` and it seems to be fine but then when I try to build scalapack with it, linking with the static libflame, building the tests/examples fail with

```
.../lib/libflame.a(FLA_hetrd.o):FLA_hetrd.c:function ssytrd_: error: undefined reference to 'ssytrd_check'
.../lib/libflame.a(FLA_hetrd.o):FLA_hetrd.c:function dsytrd_: error: undefined reference to 'dsytrd_check'
.../lib/libflame.a(FLA_hetrd.o):FLA_hetrd.c:function ssytd2_: error: undefined reference to 'ssytd2_check'
.../lib/libflame.a(FLA_hetrd.o):FLA_hetrd.c:function dsytd2_: error: undefined reference to 'dsytd2_check'
```
(I suppose this is simply the first case where it fails, all the `_check` symbols seem to be missing form the static library, from the output of `nm`)

If I build libflame with `--enable-dynamic-build` and build scalapack linking with the dynamic libflame, everything seems to work.

**Comment by fgvanzee** [comment]
Hi @migueldiascosta, thanks for this feedback and your interest in libflame. I'll try to look into this soon. (I've been on vacation and am just now getting back.)

**Comment by fgvanzee** [comment]
@migueldiascosta The problem seemed to date back years. It appears that the author of the lapack2flame compatibility layer erroneously named the source files that contained the `_check()` functions the same as the files containing the actual operation (e.g. `zhetrd.c`). Of course, they both got compiled with a simple `.c` to `.o` translation. Thus, when the static archiver archived the object files, the one that got archived second would overwrite the one archived first. (Interestingly, whether `--enable-max-arg-list-hack` is used may have been determining which one gets archived first, though either order would have been problematic.)

I think commit d2a8419 fixes this issue. Please try it out and let me know.

**Comment by migueldiascosta** [comment]
thanks @fgvanzee - the filename issue does seem to be the problem. However, now I'm getting an ` undefined reference to 'chetrd_'` (and again, with the dynamic library it works)

Inspecting the library for `chetrd`, I see

```
$ nm libflame.a | grep chetrd
chetrd_check.o:
0000000000000000 T chetrd_check
                 U chetrd_
                 U chetrd_
chetrd.o:
0000000000000000 T chetrd_fla
                 U chetrd_
                 U chetrd_
```

but for instance for `zhetrd`,

```
$ nm libflame.a | grep zhetrd
zhetrd_check.o:
0000000000000000 T zhetrd_check
                 U zhetrd_
                 U zhetrd_
                 U zhetrd_
                 U zhetrd_
zhetrd.o:
0000000000000000 T zhetrd_
zhetrd.o:
0000000000000000 T zhetrd_fla
```

why would `chetrd` and `zhetrd` be packaged differently?

**Comment by fgvanzee** [comment]
@migueldiascosta Thanks for your additional feedback. You're right that there were additional instances of object file collisions. (Once again, dissimilarly-named functions were placed in similarly-named source files.) Try 57e6459 and let me know.

**Comment by migueldiascosta** [comment]
@fgvanzee success, thanks! :)

Btw, are there any plans for a release? (last one was in 2014?)

**Comment by fgvanzee** [comment]
@migueldiascosta For now, I have no plans for a new official release. That could change in the short-term, though.

May I ask how a release (or its absence) affects your work?

**Comment by migueldiascosta** [comment]
@fgvanzee right now I'm merely trying out different combinations of linear algebra libraries, so right now it doesn't

but if I were to consider defining and using a toolchain [1] including libflame and maintaining a software stack based on it, releases would matter (dependencies are hell even *with* proper releases, semantic versioning, etc., ...)

[1] in this context, https://easybuild.readthedocs.io/en/latest/Concepts_and_Terminology.html#toolchains

**Comment by fgvanzee** [comment]
@migueldiascosta Thanks for that background. I'll certainly take this into consideration.

Just know that libflame is currently in "maintenance mode"; most of my time these days is being spent on BLIS development. So, you shouldn't expect any major changes to libflame in the near future. (Maybe that's actually a good thing in your view?)

Someday, I aim to begin reimplementing key parts of libflame either within BLIS or as a new, successor library. In any event, please stay in touch!

**Comment by dvdesolve** [comment]
I think I've faced the same issue. I'm trying to compile GAMESS with libflame and BLIS. However on linking stage of GAMESS (when BLIS and libflame should be picked up) I have the following errors:
```
/usr/bin/ld: cpmchf.o: in function `cpqrproj_':
/home/viktor/build/src/gamess-bin/object/cpmchf.f:24749: undefined reference to `dgeqrf_'
/usr/bin/ld: cpmchf.o: in function `cpeigen_':
/home/viktor/build/src/gamess-bin/object/cpmchf.f:24843: undefined reference to `dgeev_'
/usr/bin/ld: cpmchf.o: in function `cpgmres1_':
/home/viktor/build/src/gamess-bin/object/cpmchf.f:22972: undefined reference to `dgels_'
/usr/bin/ld: cpmchf.o: in function `cpgcro_':
/home/viktor/build/src/gamess-bin/object/cpmchf.f:22601: undefined reference to `dgels_'
/usr/bin/ld: cpmchf.o: in function `cpgcrodr_':
/home/viktor/build/src/gamess-bin/object/cpmchf.f:22040: undefined reference to `dgels_'
/usr/bin/ld: dftbgr.o: in function `dftb_mfrz_':
/home/viktor/build/src/gamess-bin/object/dftbgr.f:2311: undefined reference to `dtrtri_'
/usr/bin/ld: dftbx.o: in function `dftbx_':
/home/viktor/build/src/gamess-bin/object/dftbx.f:1503: undefined reference to `dpotrf_'
/usr/bin/ld: eaipcc.o: in function `ipselvec_':
/home/viktor/build/src/gamess-bin/object/eaipcc.f:7406: undefined reference to `dgeev_'
/usr/bin/ld: eaipcc.o: in function `ipinit_':
/home/viktor/build/src/gamess-bin/object/eaipcc.f:8164: undefined reference to `dgeev_'
/usr/bin/ld: eaipcc.o: in function `easelvec_':
/home/viktor/build/src/gamess-bin/object/eaipcc.f:708: undefined reference to `dgeev_'
/usr/bin/ld: eaipcc.o: in function `eainit_':
/home/viktor/build/src/gamess-bin/object/eaipcc.f:5206: undefined reference to `dgeev_'
/usr/bin/ld: eomcc.o: in function `ccnos_':
/home/viktor/build/src/gamess-bin/object/eomcc.f:9047: undefined reference to `dgeev_'
/usr/bin/ld: eomcc.o:/home/viktor/build/src/gamess-bin/object/eomcc.f:7715: more undefined references to `dgeev_' follow
/usr/bin/ld: ffield.o: in function `fitdpx_':
/home/viktor/build/src/gamess-bin/object/ffield.f:1630: undefined reference to `dgels_'
/usr/bin/ld: fmoafo.o: in function `dftb_urot_':
/home/viktor/build/src/gamess-bin/object/fmoafo.f:51: undefined reference to `dgesvd_'
/usr/bin/ld: /home/viktor/build/src/gamess-bin/object/fmoafo.f:76: undefined reference to `dgesvd_'
/usr/bin/ld: locsvd.o: in function `local_ppasvd_':
/home/viktor/build/src/gamess-bin/object/locsvd.f:1868: undefined reference to `dgesvd_'
/usr/bin/ld: locsvd.o: in function `local_ppasvdcore_':
/home/viktor/build/src/gamess-bin/object/locsvd.f:1292: undefined reference to `dgesvd_'
/usr/bin/ld: mm23.o: in function `diaghnn_':
/home/viktor/build/src/gamess-bin/object/mm23.f:2687: undefined reference to `dgeev_'
/usr/bin/ld: mm23.o: in function `diags_':
/home/viktor/build/src/gamess-bin/object/mm23.f:3093: undefined reference to `dgeev_'
/usr/bin/ld: mm23.o: in function `ciinit_':
/home/viktor/build/src/gamess-bin/object/mm23.f:1896: undefined reference to `dgeev_'
/usr/bin/ld: nebpath.o: in function `nebanglr_':
/home/viktor/build/src/gamess-bin/object/nebpath.f:1507: undefined reference to `dgels_'
/usr/bin/ld: rimp2.o: in function `rimp2vinv_':
/home/viktor/build/src/gamess-bin/object/rimp2.f:5457: undefined reference to `dpotrf_'
/usr/bin/ld: /home/viktor/build/src/gamess-bin/object/rimp2.f:5469: undefined reference to `dtrtri_'
/usr/bin/ld: rimp2grd.o: in function `rimp2_cholesky_decompose_vxx_':
/home/viktor/build/src/gamess-bin/object/rimp2grd.F90:4095: undefined reference to `dpotrf_'
/usr/bin/ld: /home/viktor/build/src/gamess-bin/object/rimp2grd.F90:4099: undefined reference to `dtrtri_'
/usr/bin/ld: roeom.o: in function `eomselvec_':
/home/viktor/build/src/gamess-bin/object/roeom.f:817: undefined reference to `dgeev_'
/usr/bin/ld: roeom.o: in function `opeominit_':
/home/viktor/build/src/gamess-bin/object/roeom.f:1488: undefined reference to `dgeev_'
/usr/bin/ld: solib.o: in function `hsores_':
/home/viktor/build/src/gamess-bin/object/solib.f:429: undefined reference to `zheev_'
/usr/bin/ld: solib.o: in function `spnjz_':
/home/viktor/build/src/gamess-bin/object/solib.f:2096: undefined reference to `zheev_'
/usr/bin/ld: /home/viktor/build/src/gamess-bin/object/solib.f:1988: undefined reference to `zheev_'
/usr/bin/ld: sozeff.o: in function `sortso_':
/home/viktor/build/src/gamess-bin/object/sozeff.f:2133: undefined reference to `zheev_'
/usr/bin/ld: sozeff.o: in function `spnory_':
/home/viktor/build/src/gamess-bin/object/sozeff.f:1634: undefined reference to `zheev_'
/usr/bin/ld: symorb.o:/home/viktor/build/src/gamess-bin/object/symorb.f:3382: more undefined references to `zheev_' follow
/usr/bin/ld: tdxitr.o: in function `slvleqsvd_':
/home/viktor/build/src/gamess-bin/object/tdxitr.f:4068: undefined reference to `dgesvd_'
/usr/bin/ld: /home/viktor/build/src/gamess-bin/object/tdxitr.f:4074: undefined reference to `dgesvd_'
```

GAMESS uses static versions of libraries. However, if I add `-llapack` to GAMESS' linker flags them I'm able to get proper executable

**Comment by fgvanzee** [comment]
@dvdesolve Can you please your configure command line?

**Comment by dvdesolve** [comment]
I suppose you mean configure line for libflame:
```
./configure --prefix=/usr --enable-static-build --enable-dynamic-build --enable-multithreading=openmp --enable-supermatrix --enable-max-arg-list-hack
```

**Comment by fgvanzee** [comment]
@dvdesolve I think your problem has an easy fix. The symbols you're missing are those of LAPACK routines. libflame does *not* build the lapack2flame compatibility layer by default. You have to enable it with `--enable-lapack2flame`.

**Comment by dvdesolve** [comment]
Oh, thank you! It fixed my problem! Just forgot to add this parameter
