### ISSUE TITLE
out of source build is not supported?

### ISSUE THREAD

**Issue by oroppas** [flame/libflame#18]
if I build out of source

```
../libflame/configure --prefix=/usr ...
```

I get

```
cat: version: No such file or directory
...
cat: ./so_version: No such file or directory
cat: ./so_version: No such file or directory
...
../libflame/configure: line8496: build/update-version-file.sh: No such file or directory
...
```
etc.

Can I safely ignore these messages?

**Comment by fgvanzee** [comment]
@oroppas Thanks for this report. No, you probably shouldn't ignore these messages. As I mentioned in issue #16, the current treatment of the `version` file doesn't allow out-of-tree builds. I will tinker with this to see if there is an easy fix.

**Comment by fgvanzee** [comment]
@oroppas Well, it wasn't really an easy fix, but it's done now; commit 588bdd1 should support out-of-tree builds. Thanks again for your feedback. Please let me know if you encounter any further issues.

**Comment by fgvanzee** [comment]
BTW, you'll want to try the head of the `master` branch; I've since committed d2a8419 as part of issue #17, which fixes a couple issues with the lapack2flame layer, one of which was introduced in 588bdd1.

**Comment by oroppas** [comment]
Great. I can build out of tree. Thanks!
