### ISSUE TITLE
undefined symbol: dpotrf_

### ISSUE THREAD

**Issue by setht** [flame/libflame#20]
Hi, I've ran the install of libflame and when I switch the lapack to libflame and run R, I get this message.

```
Error: package or namespace load failed for ‘stats’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib/R/library/stats/libs/stats.so':
  /usr/lib/R/library/stats/libs/stats.so: undefined symbol: dpotrf_
During startup - Warning message:
package ‘stats’ in options("defaultPackages") was not found 

```

I've just downloaded the latest version from github. I also run into this error when I try to make with the standard config ./run-conf/run-configure.sh:
`make: execvp: /usr/bin/env: Argument list too long`

But when I adjust the run-configure.sh to include:
`--enable-max-arg-list-hack \`
I receive this error, when running configure
`./run-conf/run-configure.sh: line 42: --enable-max-arg-list-hack: command not found`

**Comment by fgvanzee** [comment]
Hi @setht, thanks for your feedback.

I can't really help you troubleshoot R, but I will say that I've confirmed that `dpotrf_()` is part of libflame as of 57e6459:
```
$ ./configure
$ make
$ nm lib/x86_64-unknown-linux-gnu/libflame.a | grep potrf
FLA_potrf.o:
0000000000000280 T cpotrf_
                 U cpotrf_check
0000000000000140 T dpotrf_
                 U dpotrf_check
0000000000000000 T spotrf_
                 U spotrf_check
00000000000003c0 T zpotrf_
                 U zpotrf_check
...
```
The shared library seems to have it too:
```
$ nm lib/x86_64-unknown-linux-gnu/libflame.so | grep potrf
00000000000ad150 T cpotrf_
00000000000b4b70 T cpotrf_check
00000000000ad010 T dpotrf_
00000000000bd330 T dpotrf_check
00000000000aced0 T spotrf_
00000000000c3f80 T spotrf_check
00000000000ad290 T zpotrf_
00000000000c97c0 T zpotrf_check
```
As for the `--enable-max-arg-list-hack` option, double-check your `run-configure.sh` and make sure there are no trailing spaces after the backslash characters `\`. When I inserted one into my script, I was able to reproduce a similar error message:
```
$ ./run-conf/run-configure.sh 
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type:  
checking build system type... config.sub: missing argument
Try `config.sub --help' for more information.
configure: error: /bin/bash build/ac-utils/config.sub   failed
./run-conf/run-configure.sh: line 42: --enable-non-critical-code: command not found
```
In shell syntax, the backslash character `\`, as a line continuation, must always be the last character on the line.

**Comment by fgvanzee** [comment]
After editing my post above to show use of `--enable-lapack2flame`, it occurred to me that I didn't confirm that you were using this `configure` option. The LAPACK compatibility layer is disabled by default and must be enabled at configure-time via this option.

**Comment by setht** [comment]
Yes this was exactly what was happening, this resolved it. Thanks.
