### ISSUE TITLE
Unable to build on macOS

### ISSUE THREAD

**Issue by adamjstewart** [flame/libflame#23]
I've tried building both the 5.2.0 release as well as the master branch, but nothing will build for me on macOS 10.14.6 with Clang 10.0.1. Every time, I get the following error:
```
Archiving lib/x86_64-apple-darwin18.7.0/libflame.a
Dynamically linking lib/x86_64-apple-darwin18.7.0/libflame.so
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/x86_64-apple-darwin18.7.0/libflame.so] Error 1
```
I'm building with the following configure options:
```
--enable-lapack2flame --enable-static-build --enable-dynamic-build --disable-debug --enable-multithreading=no --disable-supermatrix --enable-max-arg-list-hack
```
For more information, see:

- [build log](https://github.com/flame/libflame/files/3629323/spack-build-out.txt)
- [build env](https://github.com/flame/libflame/files/3629324/spack-build-env.txt)

I also saw #7 but this appears to be an unrelated issue.

**Comment by fgvanzee** [comment]
@adamjstewart Give 6dd3c19 a try. This patch adds build system logic from BLIS to (hopefully) use the right linker flags to build shared libraries on OS X / Darwin.

**Comment by adamjstewart** [comment]
@fgvanzee I'm seeing the following error:
```console
$ make
Makefile:148: *** extraneous `endif'.  Stop.
```

**Comment by fgvanzee** [comment]
Thanks, @adamjstewart. Try 0b0ef6d.

**Comment by adamjstewart** [comment]
Thanks again @fgvanzee, with these commits I can now build `libflame` on macOS! I'll test on Linux and try building NumPy with BLIS/libflame as well.

**Comment by fgvanzee** [comment]
You're welcome. Thanks for your feedback and patience. (You happened to reach out to us during a busy time of year; we just finished our annual "BLIS Retreat" workshop.)
