### ISSUE TITLE
Configure errors with OpenMP

### ISSUE THREAD

**Issue by phu0ngng** [flame/libflame#27]
Dear libflame developers,

I tried to compile libflame either master branch or v.5.2.0.
For compiling from the source code, I did:
```
./configure --prefix=/home/software/libflame --enable-multithreading=openmp
```
For installation with spack, I did:
```
spack install libflame threads=openmp
```
Both gave the same error:
```
checking whether user requested support for multithreading... yes
checking user-requested multithreading model... openmp
checking for (guessing) OpenMP flags for /home/software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/bin/gcc... unknown
configure: error: configure doesn't know what flag to give /home/software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/bin/gcc in order to enable OpenMP support. Please submit a bug report to the FLAME developers.
```
Do you have any suggestions?

**Comment by phu0ngng** [comment]
@fgvanzee 
[](url)
[configure_out.txt](https://github.com/flame/libflame/files/3752581/configure_out.txt)
[gcc-9.2.0-modulefile.txt](https://github.com/flame/libflame/files/3752588/gcc-9.2.0-modulefile.txt)
I will keep in mind to not discuss things relate to SPACK.
This is the output from configure and the env_set for gcc.

**Comment by fgvanzee** [comment]
@phu0ngng Thanks for that output. Here's the line I was looking for:
```
configure: CC environment variable is set to /home/software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/bin/gcc, which will override --with-cc option and default search list for C compiler.
```
I was able to reproduce your issue on my side and fashion a fix in 1188aa4. Please give it a try.

**Comment by phu0ngng** [comment]
It worked. Thank you.

**Comment by fgvanzee** [comment]
You're welcome. Thanks for your feedback!
