### ISSUE TITLE
`collect2: fatal error: execvp: Argument list too long` error when building dynamic library

### ISSUE THREAD

**Issue by kyungminlee** [flame/libflame#29]
It seems that collect2 still calls execvp with many arguments, even when I use `--enable-max-arg-list-hack` and supply the list of files in a file to the linker. I get the following error message when I try to build libflame on macOS in Homebrew's superenv:

```
kyungminlee@MBP libflame-20191206-16245-13p44gs % make -n
echo "Dynamically linking lib/x86_64-apple-darwin19.0.0/libflame.dylib"
gcc-9 -dynamiclib -Wl,-install_name,libflame.1.dylib -L/Users/kyungminlee/.brew/opt/blis/lib  -L/Users/kyungminlee/.brew/opt/blis/lib -L/Users/kyungminlee/.brew/Cellar/gcc/9.2.0_2/lib/gcc/9/gcc/x86_64-apple-darwin19/9.2.0 -L/Users/kyungminlee/.brew/Cellar/gcc/9.2.0_2/lib/gcc/9/gcc/x86_64-apple-darwin19/9.2.0/../../.. -lblis -lgfortran -lquadmath -lm -lpthread -o lib/x86_64-apple-darwin19.0.0/libflame.dylib @ar_obj_list
echo "Creating symlink lib/x86_64-apple-darwin19.0.0/libflame.1.dylib"
ln -sf libflame.dylib libflame.1.dylib.loc
mv libflame.1.dylib.loc ./lib/x86_64-apple-darwin19.0.0/libflame.1.dylib
kyungminlee@MBP libflame-20191206-16245-13p44gs % make
Dynamically linking lib/x86_64-apple-darwin19.0.0/libflame.dylib
collect2: fatal error: execvp: Argument list too long
compilation terminated.
make: *** [lib/x86_64-apple-darwin19.0.0/libflame.dylib] Error 1
kyungminlee@MBP libflame-20191206-16245-13p44gs % gcc-9 -dynamiclib -Wl,-install_name,libflame.1.dylib -L/Users/kyungminlee/.brew/opt/blis/lib  -L/Users/kyungminlee/.brew/opt/blis/lib -L/Users/kyungminlee/.brew/Cellar/gcc/9.2.0_2/lib/gcc/9/gcc/x86_64-apple-darwin19/9.2.0 -L/Users/kyungminlee/.brew/Cellar/gcc/9.2.0_2/lib/gcc/9/gcc/x86_64-apple-darwin19/9.2.0/../../.. -lblis -lgfortran -lquadmath -lm -lpthread -o lib/x86_64-apple-darwin19.0.0/libflame.dylib @ar_obj_list
collect2: fatal error: execvp: Argument list too long
compilation terminated.
kyungminlee@MBP libflame-20191206-16245-13p44gs % 
```

The configure flags are `--disable-debug --enable-verbose-make-output --enable-dynamic-build --enable-lapack2flame --enable-max-arg-list-hack --enable-supermatrix --enable-multithreading=pthreads`.

How about using the same hack as the static library, and then passing the static library to the linker? Something like the following may work
```
$(CAT) $(AR_OBJ_LIST_FILE) | xargs -n$(AR_CHUNK_SIZE) $(AR) $(ARFLAGS) $(LIBFLAME_A)
$(LINKER) $(SOFLAGS) $(LDFLAGS) -o $@ -Wl,-force_load,$(LIBFLAME_A)
```

**Comment by fgvanzee** [comment]
@kyungminlee Thanks for your interest in libflame, and for this issue report.

> How about using the same hack as the static library, and then passing the static library to the linker? 

I welcome you to try this out yourself. I don't have convenient access to OS X and thus would not be able to confirm whether this (or any) fix addresses your problem. (I vaguely recall that there is a reason that the static and dynamic targets use different implementations for the `ARG_MAX` hacks, but, I don't remember why at the moment.)

**Comment by kyungminlee** [comment]
The above PR seems to work well.

**Comment by kyungminlee** [comment]
I wasn't aware that `-force_load` does not work for GNU ld. In linux, it should be `--whole-archive` instead.
