### ISSUE TITLE
linkage problem due to flag order in Makefile

### ISSUE THREAD

**Issue by kyungminlee** [flame/libflame#32]
For proper linkage of the dynamic libraries, LDFLAGS should be placed at the end when linking, 
e.g. 
https://github.com/flame/libflame/blob/fcdb12b04147d8306e330c1c8e5fd1bda23da54e/Makefile#L588

should write
```
 @$(LINKER) $(SOFLAGS) -o $@ $^ $(LDFLAGS) 
```
and other lines whenever a linker is invoked.

**Comment by fgvanzee** [comment]
Sounds fine, @kyungminlee. Should this happen for the `ARG_MAX` hack case as well?
https://github.com/flame/libflame/blob/fcdb12b04147d8306e330c1c8e5fd1bda23da54e/Makefile#L583
(Linux case above is shown; there is a Darwin case too.)

**Comment by kyungminlee** [comment]
Yes. It applies to lines 567, 569, 574, 581, 583, and 588. I've created PR https://github.com/flame/libflame/pull/33

**Comment by fgvanzee** [comment]
@kyungminlee Is there anything else left for this issue?

**Comment by kyungminlee** [comment]
@fgvanzee No. This issue has been resolved. I am closing it.
