### ISSUE TITLE
Invalid Makefile generated by configure

### ISSUE THREAD

**Issue by poulson** [flame/libflame#4]
After a vanilla ``./configure`` call with the current dev branch on a recent version of Ubuntu (15.04), running ``make`` immediately fails with the following output:
   ``Makefile:394: *** recipe commences before first target.  Stop.``

The relevant line is:

           @echo "Archiving $@"

and it is surrounded by:

    # --- Static library archiver rules for libflame ---
    $(MK_ALL_FLAMEC_LIB): $(MK_ALL_FLAMEC_OBJS)
    define EOL
     
    
    endef
    ifeq ($(FLA_ENABLE_VERBOSE_MAKE_OUTPUT),yes)
    ifeq ($(FLA_ENABLE_MAX_ARG_LIST_HACK),yes)
            @$(eval ar_args:=)
            $(foreach obj,$?,$(eval ar_args+=$(obj))$(if $(word 2048,$(ar_args)),$(AR) $(ARFLAGS) $@ $(ar_args)$(EOL)$(eval ar_args:=)))
            $(AR) $(ARFLAGS) $@ $(ar_args)
    #       echo $(ARFLAGS) $@ > $(AR_ARG_LIST_FILE)
    #       $(CAT) $(AR_OBJ_LIST_FILE) >> $(AR_ARG_LIST_FILE)
    #       $(AR) @$(AR_ARG_LIST_FILE)
            $(RANLIB) $@
    else
            $(AR) $(ARFLAGS) $@ $?
            $(RANLIB) $@
    endif
            mkdir -p include_local
            cp -f $(MK_HEADER_FILES) include_local
    else
            @echo "Archiving $@"
    ifeq ($(FLA_ENABLE_MAX_ARG_LIST_HACK),yes)
            @$(eval ar_args:=)
            @$(foreach obj,$?,$(eval ar_args+=$(obj))$(if $(word 2048,$(ar_args)),@$(AR) $(ARFLAGS) $@ $(ar_args)$(EOL)$(eval ar_args:=)))
            @$(AR) $(ARFLAGS) $@ $(ar_args)
    #       @echo $(ARFLAGS) $@ > $(AR_ARG_LIST_FILE)
    #       @$(CAT) $(AR_OBJ_LIST_FILE) >> $(AR_ARG_LIST_FILE)
    #       @$(AR) @$(AR_ARG_LIST_FILE)
            @$(RANLIB) $@
    else
            @$(AR) $(ARFLAGS) $@ $?
            @$(RANLIB) $@
    endif
            @mkdir -p include_local
            @cp -f $(MK_HEADER_FILES) include_local
    endif

My guess is that the ``define EOL`` portion might be causing Make to think that the command for the rule has ended.

**Comment by fgvanzee** [comment]
For future readers/lurkers: A workaround to this build system issue is described in a sticky topic at [libflame-discuss](http://groups.google.com/group/libflame-discuss).
