### ISSUE TITLE
Build support for Cray programming environment

### ISSUE THREAD

**Issue by lukebroskop** [flame/libflame#81]
Hi, in order to build libflame with Cray's compiler wrappers (CC/cc/ftn or crayCC,craycc,crayftn) I need to apply the following patch to `configure`:

```
diff --git a/configure b/configure
index 33a67b14..43662526 100755
--- a/configure
+++ b/configure
@@ -3481,7 +3481,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-               CC_VENDOR=$(echo "$CC" | egrep -o 'icc|gcc|clang|emcc|pnacl|IBM' | { read first rest ; echo $first ; })
+               CC_VENDOR=$(echo "$CC" | egrep -o 'icc|gcc|clang|emcc|pnacl|IBM|cc|craycc' | { read first rest ; echo $first ; })
 
        if test "${CC_VENDOR}" = "" ; then
                as_fn_error $? "configure can't determine the compiler vendor for $CC. Please submit a bug report to the FLAME developers." "$LINENO" 5
@@ -6525,6 +6525,9 @@ $as_echo_n "checking for (guessing) OpenMP flags for ${CC_VENDOR}... " >&6; }
                                *xlc*)
                        fla_c_openmp_flags='-qsmp=omp'
                ;;
+                                cc)
+                        fla_c_openmp_flags='-fopenmp'
+                ;;
                                *)
                        fla_c_openmp_flags='unknown'
                ;;
```
would it be possible to make these changes upstream?

**Comment by lukebroskop** [comment]
@iotamudelta

**Comment by lukebroskop** [comment]
@fgvanzee

**Comment by fgvanzee** [comment]
@lukebroskop 
```
+                                cc)
+                        fla_c_openmp_flags='-fopenmp'
+                ;;
```
Would `craycc` work here instead? Or does it need to be `cc`? (This `case` statement uses the "compiler vendor" variable, mind you, not the variable with the actual name of the compiler. And the first part of your patch seems to support `craycc`.)

**Comment by fgvanzee** [comment]
Or maybe you want to support both `cc` and `craycc` vendor names?

**Comment by lukebroskop** [comment]
I'm trying to build with spack and here is what $CC is:
```
/tmp/lukebr/spack-stage/spack-stage-libflame-5.2.0-qm3krx5boa2zn6eixyhkkszujcvz7zjy/spack-src> echo $CC
/autofs/nccs-svm1_proj/ven114/lukebr/spack/lib/spack/env/cce/cc
```
I don't know a good way to handle this. Perhaps if there was a configure options that would allow us to override the OpenMP compiler flag?

**Comment by fgvanzee** [comment]
Oh, hmm. I just realized that libflame is really dumb about the way it checks for cc_vendor. BLIS looks at the actual output from `--version`, I think. But here, we just parse the name.

**Comment by fgvanzee** [comment]
I think *very* few people compile with `cc`, and those that do can probably use `-fopenmp`, so I'm fine proceeding with your patch, I think.

**Comment by fgvanzee** [comment]
@lukebroskop There you go. Give it a try!

**Comment by lukebroskop** [comment]
@fgvanzee That did it. Thanks for the quick turnaround!
