### ISSUE TITLE
spack install fails while linking

### ISSUE THREAD

**Issue by moritzgubler** [flame/libflame#88]
Hi
I was trying to install liflame using spack on centos 7  using: ```spack install amdlibflame@3.1 %aocc@3.2.0```. This failed while linking with the error:

3886    ld.gold: --push-state: unknown option
3887    ld.gold: use the --help option for usage information
3888    collect2: error: ld returned 1 exit status
3889    make[1]: *** [Makefile:12: generate] Error 1
3890    make[1]: Leaving directory '/scratch/gubmor00/spack-stage/spack-stage-amdlibflame-3.1blxdx37qerueegbcdtxr5l3qt3cyvwbg/spack-src/src/aocl_dtl'
3891    make: *** [Makefile:579: src/aocl_dtl/libaocldtl.a] Error 2
3892    make: *** Waiting for unfinished jobs....

I used GNU ld version 2.27-44.base.el7_9.1. 
After upgrading to GNU ld 2.36.1 the problem went away. Is the problem caused by my initial linker being too old?

**Comment by iotamudelta** [comment]
You seem to be installing the AMD fork of libflame - not this upstream version. Hence, I'd recommend you ask your question here: https://github.com/amd/libflame - but it does indeed look like a newer linker flag is being used with your used version does not support.

**Comment by moritzgubler** [comment]
Yes, I use the amd fork of libflame. Sorry, I did not realize that there are two separate repos.
